### ISSUE TITLE
Music stops playing after clicking on loop "queue" or "now playing music"

### ISSUE THREAD

**Issue by DyrenVL** [umutxyp/MusicBot#106]
On discord i receive "interaction failed" and in the terminal i receive this:
/home/ubuntu/musicbot/node_modules/discord.js/src/client/actions/InteractionCreate.js:50
        if (channel && !channel.isTextBased()) return;
                                ^

TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/ubuntu/musicbot/node_modules/discord.js/src/client/actions/InteractionCreate.js:50:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/ubuntu/musicbot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/ubuntu/musicbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/ubuntu/musicbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/ubuntu/musicbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/ubuntu/musicbot/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/ubuntu/musicbot/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/ubuntu/musicbot/node_modules/ws/lib/websocket.js:1180:20)
    at Receiver.emit (node:events:527:28)

Node.js v17.9.0

**Comment by omgomghax** [comment]
I'm having the exact same issue where it will randomly crash with this error.
Not an expert here, but from my understanding it seems that the error is caused by the Discord.JS itself?

**Comment by DyrenVL** [comment]
@omgomghax I don't know what the problem was but redownloading the bot fixed it.
