### ISSUE TITLE
Can run /play

### ISSUE THREAD

**Issue by T7SEN** [umutxyp/MusicBot#116]
Error
TypeError [CommandInteractionOptionNoSubcommand]: No subcommand specified for interaction.
at CommandInteractionOptionResolver.getSubcommand (/root/music/node_modules/discord.js/src/structures/CommandInteractionOptionResolver.js:113:13)
at Object.run (/root/music/commands/play.js:42:37)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by T7SEN** [comment]
Now it's not giving me anything when I try the command.

![image](https://user-images.githubusercontent.com/17919973/235041518-d3d3af7b-b95d-45d3-8b71-1bef2f5bf528.png)

**Comment by chethanyadav456** [comment]
I think this issuse is solved @umutxyp close the close.

**Comment by T7SEN** [comment]
Solved you said? I went thru every single issue and saw none. How is it solved?
